const ACTIVITY_TYPES = Object.freeze({
  GROUP_CREATED: "GROUP_CREATED",
  MEMBER_ADDED: "MEMBER_ADDED",
  MEMBER_REMOVED: "MEMBER_REMOVED",
  EXPENSE_CREATED: "EXPENSE_CREATED",
  EXPENSE_UPDATED: "EXPENSE_UPDATED",
  EXPENSE_DELETED: "EXPENSE_DELETED",
  PAYMENT_CREATED: "PAYMENT_CREATED",
});

module.exports = ACTIVITY_TYPES;
