const NOTIFICATION_TYPES = Object.freeze({
  MEMBER_ADDED: "MEMBER_ADDED",
  MEMBER_REMOVED: "MEMBER_REMOVED",
  MEMBER_ROLE_CHANGED: "MEMBER_ROLE_CHANGED",
  EXPENSE_CREATED: "EXPENSE_CREATED",
  EXPENSE_UPDATED: "EXPENSE_UPDATED",
  EXPENSE_DELETED: "EXPENSE_DELETED",
  PAYMENT_CREATED: "PAYMENT_CREATED",
  REACTION_ADDED: "REACTION_ADDED",
});

module.exports = NOTIFICATION_TYPES;